/**
 * Sidebar
 */
export const CHANGE_SIDEBAR_DOCK = 'CHANGE_SIDEBAR_DOCK'

/**
 * Bots
 */
export const ADD_NEWS = 'ADD_NEWS'
export const START_CREATE_NEWS = 'START_CREATE_NEWS'
export const FINISHED_CREATE_NEWS = 'FINISHED_CREATE_NEWS'
export const FAILED_CREATE_NEWS = 'FAILED_CREATE_NEWS'

export const START_FETCH_ALL_NEWS = 'START_FETCH_ALL_NEWS'
export const FINISHED_FETCH_ALL_NEWS = 'FINISHED_FETCH_ALL_NEWS'
export const FAILED_FETCH_ALL_NEWS = 'FAILED_FETCH_ALL_NEWS'

export const START_FETCH_NEWS = 'START_FETCH_NEWS'
export const FINISHED_FETCH_NEWS = 'FINISHED_FETCH_NEWS'
export const FAILED_FETCH_NEWS = 'FAILED_FETCH_NEWS'

export const START_UPDATE_NEWS = 'START_UPDATE_NEWS'
export const FINISHED_UPDATE_NEWS = 'FINISHED_UPDATE_NEWS'
export const FAILED_UPDATE_NEWS = 'FAILED_UPDATE_NEWS'

export const START_DELETE_NEWS = 'START_DELETE_NEWS'
export const FINISHED_DELETE_NEWS = 'FINISHED_DELETE_NEWS'
export const FAILED_DELETE_NEWS = 'FAILED_DELETE_NEWS'

export const RESET_NEWS_STATE = 'RESET_NEWS_STATE'

/**
 * Generic Constants
 */
export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const CONFIG_NOTIFICATION_SYSTEM = 'CONFIG_NOTIFICATION_SYSTEM';
